openapi: 3.0.1
info:
  title: Greeter Microservice
  description: Microservice for greeting people
  contact:
    name: Marc Kohaupt
    url: http://debuglevel.de
  license:
    name: Unlicense
    url: https://unlicense.org/
  version: "0.1"
paths:
  /postalcodes:
    get:
      tags:
      - postalcodes
      summary: Get all postalcodes
      description: Get all postalcodes
      operationId: getAllPostalcodes
      parameters: []
      responses:
        default:
          description: All postalcodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetPostalcodeResponse'
    post:
      tags:
      - postalcodes
      summary: "Create a postalcode.\n This is not meant for productive use, but rather\
        \ for uploading backups."
      description: "Create a postalcode.\n This is not meant for productive use, but\
        \ rather for uploading backups."
      operationId: postOnePostalcode
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                addPostalcodeRequest:
                  $ref: '#/components/schemas/AddPostalcodeRequest'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddPostalcodeResponse'
    delete:
      tags:
      - postalcodes
      summary: Delete all postalcodes.
      description: Delete all postalcodes.
      operationId: deleteAllPostalcodes
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
  /postalcodes/{id}:
    get:
      tags:
      - postalcodes
      summary: Get a postalcode
      description: Get a postalcode
      operationId: getOnePostalcode
      parameters:
      - name: id
        in: path
        description: ID of the postalcode
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: A postalcode
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPostalcodeResponse'
    delete:
      tags:
      - postalcodes
      summary: Delete a postalcode.
      description: Delete a postalcode.
      operationId: deleteOnePostalcode
      parameters:
      - name: id
        in: path
        description: ID of the postalcode
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
  /postalcodes/populate:
    post:
      tags:
      - postalcodes
      operationId: populate
      parameters: []
      responses:
        default:
          description: populate default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/void'
  /streets:
    get:
      tags:
      - streets
      summary: Get all streets
      description: Get all streets
      operationId: getAllStreets
      parameters:
      - name: postalcode
        in: query
        required: false
        schema:
          type: string
          nullable: true
      - name: streetname
        in: query
        required: false
        schema:
          type: string
          nullable: true
      responses:
        default:
          description: All streets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetStreetResponse'
    post:
      tags:
      - streets
      summary: "Create a street.\n This is not meant for productive use, but rather\
        \ for uploading backups."
      description: "Create a street.\n This is not meant for productive use, but rather\
        \ for uploading backups."
      operationId: postOneStreet
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                addStreetRequest:
                  $ref: '#/components/schemas/AddStreetRequest'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddStreetResponse'
    delete:
      tags:
      - streets
      summary: Delete all streets.
      description: Delete all streets.
      operationId: deleteAllStreets
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
  /streets/{id}:
    get:
      tags:
      - streets
      summary: Get a street
      description: Get a street
      operationId: getOneStreet
      parameters:
      - name: id
        in: path
        description: ID of the street
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: A street
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStreetResponse'
    delete:
      tags:
      - streets
      summary: Delete a street.
      description: Delete a street.
      operationId: deleteOneStreet
      parameters:
      - name: id
        in: path
        description: ID of the street
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
  /streets/populate:
    post:
      tags:
      - streets
      operationId: populate
      parameters: []
      responses:
        default:
          description: populate default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/void'
components:
  schemas:
    GetPostalcodeResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          description: The actual value of the postal code
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
        note:
          type: string
          description: A note which might be available from some providers
          nullable: true
        createdOn:
          type: string
          description: When created in the database
          format: date-time
        lastModifiedOn:
          type: string
          description: When last modified in the database
          format: date-time
    Unit:
      type: object
    AddPostalcodeResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          description: The actual value of the postal code
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
        note:
          type: string
          description: A note which might be available from some providers
          nullable: true
        createdOn:
          type: string
          description: When created in the database
          format: date-time
        lastModifiedOn:
          type: string
          description: When last modified in the database
          format: date-time
    AddPostalcodeRequest:
      type: object
      properties:
        code:
          type: string
          description: The actual value of the postal code
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
        note:
          type: string
          description: A note which might be available from some providers
          nullable: true
    void:
      type: object
    GetStreetResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        postalcode:
          type: string
          description: The postal code
        streetname:
          type: string
          description: The name of the street
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
        createdOn:
          type: string
          description: When created in the database
          format: date-time
        lastModifiedOn:
          type: string
          description: When last modified in the database
          format: date-time
    AddStreetResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        postalcode:
          type: string
          description: The postal code
        streetname:
          type: string
          description: The name of the street
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
        createdOn:
          type: string
          description: When created in the database
          format: date-time
        lastModifiedOn:
          type: string
          description: When last modified in the database
          format: date-time
    AddStreetRequest:
      type: object
      properties:
        postalcode:
          type: string
          description: The postal code
        streetname:
          type: string
          description: The name of the street
        centerLatitude:
          type: number
          description: Latitude of the center of the postal code area
          format: double
          nullable: true
        centerLongitude:
          type: number
          description: Longitude of the center of the postal code area
          format: double
          nullable: true
